github_url: https://github.com/dhavalkapil
google_url: https://plus.google.com/+DhavalKapildk
twitter_url: https://twitter.com/dhaval_kapil
linkedin_url: https://in.linkedin.com/in/dhavalkapil
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
resume_url: /resume.pdf
rss_url: /atom.xml
sitemap_url: /sitemap.xml