facebook_url: https://www.facebook.com/dhaval.kapil
github_url: https://github.com/dhavalkapil
google_url: https://plus.google.com/+DhavalKapildk
twitter_url: https://twitter.com/dhaval_kapil
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
resume_url: /resume.pdf