github_url: https://github.com/Tamcode
twitter_url: https://twitter.com/TamCoded
linkedin_url: https://in.linkedin.com/in/tamanna-goyal70
about_url: /about/
archive_url: /archive/
projects_url: /projects/
contact_url: /contact/
disclaimer_url: /disclaimer/
resume_url: /resume.pdf
sitemap_url: /sitemap.xml
