facebook_url: https://www.facebook.com/dhaval.kapil
about_url: http://about.me/dhavalkapil
github_url: https://github.com/dhavalkapil
google_url: https://plus.google.com/+DhavalKapildk
twitter_url: https://twitter.com/dhaval_kapil
archive_url: /archive/